---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
  Test: 0
configure_requires:
  ExtUtils::MakeMaker: 6.3
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Cmd
no_index:
  directory:
    - t
    - inc
requires:
  Config: 0
  Cwd: 0
  Exporter: 0
  File::Basename: 0
  File::Copy: 0
  File::Find: 0
  File::Spec: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/neilbowers/Test-Cmd.git
version: 1.05_02
